### ISSUE TITLE
Color control and data volume issues with Gaussian_model_isotropic

### ISSUE THREAD

**Issue by X-Probiotics** [Colmar-zlicheng/Spring-Gaus#6]
Thank you for your excellent work, this is a very interesting project. And congratulations on your work being accepted by ECCV!! I have a few questions regarding debugging the code:

（1）I noticed that in the **Gaussian_model_isotropic** you replaced the original 3DGS's  **Gaussian_model** use of 48-channel spherical harmonics for color control with a direct use of 3-channel RGB. What was the purpose of this change? Additionally, besides color, are there any other differences between the **Gaussian_model_isotropic** and the original **Gaussian_model**?

![6772e43256906e9d0e5d774516f831b](https://github.com/Colmar-zlicheng/Spring-Gaus/assets/162662507/981a2ce3-747c-44d8-866c-b5ea4f3c36da)

（2）I attempted to import the static Gaussian model generated by the original 3DGS, which includes color information across 48 channels in point_cloud.ply, into the registration network. However, during rendering, there was a massive increase in data volume, resulting in memory overload and rendering failure. Why does the registration network require so much data for rendering the static 3DGS model?

<img width="966" alt="761486bc45c033e8db1c8259762bc03" src="https://github.com/Colmar-zlicheng/Spring-Gaus/assets/162662507/5b240554-5727-4756-8282-25145010466a">

**Comment by Colmar-zlicheng** [comment]
Hi, thank you

1.  That's a simplifying assumption, because its hard to compute the rotation of each kernels in Spring-Mass system, so we assume that each Gaussian is a sphere of isotropic terms.

2. We only optimize a few parameters in registration network, the CUDA memory should be very close to static reconstruction. How many Gaussian kernels do you have?

**Comment by X-Probiotics** [comment]
> Hi, thank you
> 
> 1. That's a simplifying assumption, because its hard to compute the rotation of each kernels in Spring-Mass system, so we assume that each Gaussian is a sphere of isotropic terms.
> 2. We only optimize a few parameters in registration network, the CUDA memory should be very close to static reconstruction. How many Gaussian kernels do you have?

Thank you very much for your response. I have checked the input Gaussian models and indeed found the issue of excessive kernels. Once resolved, registration can proceed normally.

Additionally, I have another question: During the registration phase, it's necessary to assign an initial [R, T, S] to the 3D Gaussian model. How do you obtain this set of init_R, T, S? Is it manually set?
<img width="632" alt="1" src="https://github.com/Colmar-zlicheng/Spring-Gaus/assets/162662507/8f1c464a-fc92-47e3-99bc-1997bf88e3c6">

**Comment by Colmar-zlicheng** [comment]
In our real world experiments, I use the first frame of each video for a coarse reconstruction just to obtain an approximate location of the object (which is the INIT_T I set). For INIT_R and INIT_S, just manually set.

**Comment by Mysterious-handsome-man** [comment]
I would like to discuss another interesting scenario with you: 

In the context of a rigid body where only gravity is considered during motion, neglecting all other forces (no air resistance, no elastic forces due to deformation), when optimizing a 3D Gaussian model, the dynamics equation of the model's motion is jointly optimized with the 3D Gaussian model.

In this background, what do you think are the challenges? Is it feasible to jointly optimize the parameters of the dynamics equation and the 3D Gaussian model?
